### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by vronizor** [grantmcdermott/duckdb-polars#3]
Hi @grantmcdermott ,

Thanks again for the really cool workshop — already starting to integrate it in my workflow, and it's working really well! I think you mentioned at some point you were going to include your slides? I wanted to check the slide you had on the way columnar data storage protocols and DuckDB-style data base engines worked well together.

Cheers

**Comment by grantmcdermott** [comment]
Thanks @vronizor that’s great to hear. I definitely plan to add the slides (plus a few more changes that I wanted to add). But unfortunately I’ve been slammed at work these last few weeks, so have had to push all hobbyist/OSS stuff to the backburner. I’ll get to it at some point in the next few weeks, though.

**Comment by grantmcdermott** [comment]
Closed by f4f8357ccda6e393b334f315349b02ee3137e22c

(Sorry that this took me so long)
