### ISSUE TITLE
R Polars output print

### ISSUE THREAD

**Issue by eitsupi** [grantmcdermott/duckdb-polars#4]
Although this is not required, it should be possible to change the output of R Polars to HTML that matches that of Python Polars.
https://pola-rs.github.io/r-polars/man/S3_knit_print.html

**Comment by grantmcdermott** [comment]
Thanks for the tip! Closed with 2b24ae13551123ebdbcb0ddb04ec4e2a7dec8004

P.S. Do you know if there's a way to control the number of printed lines? Right now the pretty-printed R output is significantly longer than the Python output, which makes it a little disorientating to switch between the two.

**Comment by eitsupi** [comment]
> Do you know if there's a way to control the number of printed lines? Right now the pretty-printed R output is significantly longer than the Python output, which makes it a little disorientating to switch between the two.

Thanks for pointing this out!
I was unaware that the default value for the line limit was done elsewhere.
https://github.com/pola-rs/polars/blob/d6703c409c44c72d9a1426a90d64606fc03afa54/py-polars/polars/dataframe/frame.py#L1423-L1429

I believe this will be fixed in the next release.

**Comment by grantmcdermott** [comment]
(Oops. I just saw that I accidentally hit 👎 instead of 👍 in my original response... Fixed now!)

**Comment by eitsupi** [comment]
Could you try the latest release?

**Comment by grantmcdermott** [comment]
Will do. Just waiting on some minor changes to Etienne’s PR here https://github.com/grantmcdermott/duckdb-polars/pull/8

**Comment by grantmcdermott** [comment]
Looks good thanks! https://grantmcdermott.com/duckdb-polars/polars-rpy.html#aggregation
